### ISSUE TITLE
View which Testers a Product is tested at

### ISSUE THREAD

**Issue by nickwbarber** [cs340-summer2020-group43/cs340-proj#15]
Satisfies requirement to READ at M:M relationship

Possible implementation:
1. End-user shows intent as described in this issue
1. Client sends a request to the server for the Testers
1. Server replies with a JSON object containing the relevant information
1. Client creates HTML and populates according to the JSON data

Another possible implementation:
1. End-user shows intent as described in this issue
1. Client sends a request to the server for the Testers
1. Server replies with HTML (e.g. a `div` with an unordered list) for the client to insert where appropriate
1. Client inserts HTML into DOM (possibly via something like [insertAdjacentHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML))

**Comment by nickwbarber** [comment]
Regarding which implementation we ought to go with, what are you thinking, @jenniferd777?

Personally, I think the first one makes more sense since it's flexible toward whatever frontend implementation is desired.

**Comment by jenniferd777** [comment]
I think deleting the relationship between Tester and User will be good. That should be pretty easy

**Comment by nickwbarber** [comment]
Okay, but what implementation plan do you think seems best? I made a couple of suggestions, and then a couple of comments ago I made clear which one I think seems better, but I'm open to discussion of course.
