### ISSUE TITLE
Add Test Client Side

### ISSUE THREAD

**Issue by jenniferd777** [cs340-summer2020-group43/cs340-proj#23]
Add Test both Java and html

**Comment by nickwbarber** [comment]
> Add Test both Java and html

I'm not sure what this means. Do you mean that it should be possible for an end-user to add Tests to the database, and also that the likely implementation would imply writing some Javascript and some HTML?

**Comment by jenniferd777** [comment]
This is pretty much done, just need to verify it works by entering the data into the website.
