### ISSUE TITLE
Basic input validation

### ISSUE THREAD

**Issue by nickwbarber** [cs340-summer2020-group43/cs340-proj#6]
For #17

Prohibit null values where appropriate

**Comment by nickwbarber** [comment]
What also seems relevant would be informing the user when the field they've filled out conflicts with the rules of the database. One of the most crucial of these rules would be the uniqueness of primary keys. The user won't know ahead of time which field is the key, and thus that it needs to be unique.

Perhaps after the form is submitted, the server could send back a response, and based on the response, the client could display a helpful message. Relevant to #10

**Comment by jenniferd777** [comment]
I plan on it, but for now we just need to make sure that it is working. Also I have implemented some restrictions using html. 
for example under input I have placed that it is required and set max lengths, so these will notify the user before it will allow them to submit

**Comment by jenniferd777** [comment]
I just read another comment from another issue and will have to look into the checking more and avoid html checking.

**Comment by nickwbarber** [comment]
For posterity, the relevant discussion that I think you're referring to happened on 67bc9d483b1ab9489030f853e974a355d3fa23c9
